backend:
  name: github
  repo: klpoland1/gatsby-hosting

media_folder: static/assets
public_folder: assets

collections:
  - name: module_1
    label: Module 1
    folder: module_1
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  - name: module_2
    label: Module 2
    folder: module_2
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  - name: module_3
    label: Module 3
    folder: module_3
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  